/* Generated by S-function Builder */
#ifndef _MAIN_BUS_H_
#define _MAIN_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_Aceleracao_
#define _DEFINED_TYPEDEF_FOR_Aceleracao_ 
typedef struct {
  real_T acc_x;
  real_T acc_y;
  real_T acc_z;
} Aceleracao;
#endif

/* Read only - ENDS */


#endif
